<center><h1> [[ Python tutorial AtoP ]] </h1></center>

# 1. Jupyter notebook

### 주피터노트북 주요 기능
- cell type : markdown / code
- [shift]+ [enter] : cell 실행 후 아래 cell 포커싱
- [alt] + [enter] : cell 실행 후 아래 새 cell 생성
- [tab] : 자동완성

### 초심자가 알아야하는 파이썬 기능
- help(~~)
- ?~~
- type(~~)

# 2. Basic Data type

## 1) Number

### i) 다양한 숫자형 데이터의 연산자

In [17]:
#덧셈
1+5

6

In [18]:
#뺄셈
5-10

-5

In [23]:
#곱셈
3*6

18

In [25]:
# 제곱
12**2

144

In [42]:
#나눗셈
13/4

3.25

In [44]:
#나눗셈...??
13//4

3

In [54]:
#...?!
13%4    #=> Modulo operation

1

### ii) 변수 : 값을 저장하는 공간. 

In [57]:
x = 5

In [58]:
y = 7

In [60]:
x+y

12

### Q) 다음의 결과는? 그리고 왜??

In [110]:
answer = ((5+5)*10)**(1+1)

In [53]:
answer

10000

## 2) String

In [1]:
# 문자열(String)은 "혹은 '로 만들 수 있음.
str1 = "This is an apple."
str2 = 'This is also an apple.'

In [2]:
str1

'This is an apple.'

In [3]:
str2

'This is also an apple.'

In [5]:
# 이건 왜 에러..??
'I'm a pythonista.'

SyntaxError: invalid syntax (<ipython-input-5-f00fa6179620>, line 2)

### Q) 위 문제의 해결방법은..?

In [6]:
str1[0]

'T'

In [7]:
str1[1]

'h'

In [8]:
str1[0:4]

'This'

In [9]:
str1[-1]

'.'

In [10]:
"string"+"string"

'stringstring'

In [12]:
"string"*3

'stringstringstring'

## 3) List 
- 리스트명 = [요소1, 요소2, 요소3, ...]

### i) 생성

In [13]:
odd = [1, 3, 5, 7, 9]
odd

[1, 3, 5, 7, 9]

In [25]:
[ ]

[]

In [15]:
[1, 2, 3]

[1, 2, 3]

In [16]:
[1, "a", "b"]

[1, 'a', 'b']

In [17]:
[1, 2, ['Life', 'is']]

[1, 2, ['Life', 'is']]

### ii) 값 접근

In [26]:
odd

[1, 3, 5, 7, 9]

In [27]:
odd[1]

3

In [28]:
odd[:3]

[1, 3, 5]

In [29]:
odd[3:]

[7, 9]

In [30]:
# 값 변경
odd[3] = "a"

In [32]:
odd

[1, 3, 5, 'a', 9]

## 4) Tuple
- tuple명 = (요소1, 요소2, ...)
- list와 유사하지만 값 수정 불가

In [33]:
t = (1, 2, 3)
t

(1, 2, 3)

In [34]:
t[0]

1

In [35]:
t[0]=100

TypeError: 'tuple' object does not support item assignment

## 5) Dictionary
- key: value 쌍으로 이루어진 데이터 타입
- {Key1:Value1, Key2:Value2, Key3:Value3 ...}

In [36]:
my_bag = {'pencil': 3, 'laptop':1, 'book': 5}
my_bag

{'book': 5, 'laptop': 1, 'pencil': 3}

In [37]:
my_bag["pencil"]

3

In [38]:
my_bag["pencil"] = 12

In [39]:
my_bag

{'book': 5, 'laptop': 1, 'pencil': 12}

In [40]:
my_bag.keys()
#list(my_bag.keys())

dict_keys(['pencil', 'laptop', 'book'])

In [41]:
my_bag.values()

dict_values([12, 1, 5])

## 6) Set
- 집합을 처리하기 위해 만들어진 데이터 타입
- 특징 : __중복허용안함, 순서없음__
- set(~~~) 로 생성

In [46]:
s1 = set([1,2,3])
s1

{1, 2, 3}

In [47]:
s2 = set("Hello")
s2

{'H', 'e', 'l', 'o'}

In [48]:
# 값 추가
s2.add(6)
s2

{6, 'l', 'H', 'o', 'e'}

In [50]:
s2[1]

TypeError: 'set' object does not support indexing

# 4. Numpy - Numerical Python
- [Numpy](http://www.numpy.org/): core library for scientific computing in Python.
- provides a high-performance multidimensional array object, and tools for working with these arrays

http://cs231n.github.io/python-numpy-tutorial/

### Numpy 에서 제공하는 기능
- 빠르고 메모리를 효율적으로 사용하며 벡터 산술연산과 세련된 브로드캐스팅 기능을 제공하는 다차원 배열 ndarray
- 반복문을 작성할 필요없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 표준 수학 함수
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 올려진 파일을 사용하는 도구
- 선형대수, 난수 발생기, 푸리에 변환 기능.
- C, C++, 포트란으로 쓰여진 코드를 통합하는 도구.

### 패키지 불러오기
- import XXX
- import XXX as X
- from XXX import YYY
- from XXX import *

In [93]:
# Numpy 불러오기.
import numpy as np #=> numpy 패키지를 불러와서 np라는 이름으로 사용함. 기능을 사용할때마다 np.을 앞에 명시해야함.
#from numpy import * # => np. 없이 사용해도 괜찮음. 하지만 좋지않음..!

## 1) Arrays
- ndarray : 같은 종류를 담을 수 있는 포괄적인 다차원(N diemnsion) 배열 객체.
- 스칼라 원소 간의 연산에 사용하는 문법과 비슷한 방식을 사용해서 전체 데이터 블록에 수학적인 연산을 수행할 수 있게 함.
- __모든 원소는 같은 자료형 이어야함!__
- 모든 array는 각 차원의 크기를 알려주는 __shape__라는 튜플과 array에 저장된 자료형을 알려주는 __dtype__이라는 객체를 가지고 있음.

### i) 1차원 array

In [161]:
temp_list = [1,2,3]

In [162]:
arr = np.array(temp_list)

In [163]:
print(arr)

[1 2 3]


In [164]:
# arr의 자료형 출력.
print(type(arr))

<class 'numpy.ndarray'>


In [197]:
# arr의 내부에 저장된 데이터의 자료형.
print(arr.dtype)
## => 명시적으로 지정하지 않으면, np.array가 생성될 때 적절한 자료형을 추정함.

int64


In [198]:
# arr의 차원.
print(arr.ndim)

1


In [199]:
# arr의 모양을 튜플 형태로 보여줌.
print(arr.shape)

(3,)


In [200]:
# "[~~]" 를 이용해서 각각의 원소에 접근 가능.
print(arr[0])

5


In [201]:
# 각각의 원소 출력.
print(arr[0],arr[1],arr[2])

5 2 3


In [202]:
# arr의 0번째 원소에 접근하여 그 값에 5를 대입.
arr[0] = 5

In [203]:
print(arr)

[5 2 3]


### ii) n차원 array

In [204]:
# 2차원 array 생성.
temp_list2 = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(temp_list2)

In [216]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [207]:
# arr2의 차원.
print(arr2.ndim)

2


In [213]:
# 3차원 array 생성.
temp_list3 = [[[1,2,3],[4,5,6],[7,8,9]],[[10,20,30],[40,50,60],[70,80,90]]]
arr3 = np.array(temp_list3)

In [214]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]


In [217]:
# arr3의 차원.
print(arr3.ndim)

3


### iii) Numpy 배열 생성 함수

In [228]:
# 모든 원소가 0이고, shape이 (5,5)인 ndarray 생성.
arr_zero = np.zeros((5,5))
print(arr_zero)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [231]:
print(arr_zero.shape)

(5, 5)


In [230]:
# 모든 원소가 1이고, shape이 (4,4)인 ndarray 생성.
arr_one = np.ones((4,4))
print(arr_one)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [234]:
# 모든 원소가 무작위이고, shape이 (4,4)인 ndarray 생성.
# np.random.random?
arr_rd = np.random.random((5,3))
print(arr_rd)

[[ 0.65439712  0.21579772  0.20702076]
 [ 0.55550451  0.53672153  0.91484266]
 [ 0.89062986  0.21191188  0.33340855]
 [ 0.7466301   0.08774881  0.21748616]
 [ 0.23434888  0.73553813  0.42145589]]


## 2) Array Indexing
- 파이썬 list와 유사하게 동작.

### i) Slicing

In [254]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [255]:
arr_slice = arr[:2,1:3]

In [256]:
print(arr_slice)

[[2 3]
 [6 7]]


In [257]:
print( arr[0,1] )

2


In [258]:
arr_slice[0,0] = 77
arr_slice

array([[77,  3],
       [ 6,  7]])

In [259]:
print( arr[0,1] )

77


## 3) Array math

### i) Basic mathematical functions 

In [271]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [272]:
print(x)
print(y)

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]


In [273]:
# Elementwise sum
print(x + y)
print(np.add(x, y))

[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]


In [274]:
# Elementwise difference
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [275]:
# Elementwise product
print(x * y)
print( np.multiply(x, y))

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]


In [276]:
# Elementwise division
print( x / y)
print( np.divide(x, y))

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [278]:
# Elementwise square root
print( np.sqrt(x))

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


### ii) dot product

In [286]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([1,2])
w = np.array([2,1])

In [287]:
# Inner product of vectors
print( v.dot(w) )
print( np.dot(v, w) )

4
4


In [288]:
# Matrix / vector product
print( x.dot(v) )
print( np.dot(x, v) )

[ 5 11]
[ 5 11]


In [289]:
# Matrix / matrix product
print( x.dot(y))
print( np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### iii) Useful function

In [291]:
x = np.array([[1,2],[3,4]])

In [299]:
# 모든 원소의 합
print( np.sum(x) )

10


In [301]:
# 각 col의 합
print( np.sum(x, axis=0)  )

[4 6]


In [303]:
# 각 row의 합
print( np.sum(x, axis=1)  )

[3 7]


In [311]:
# 틀린그림찾기!
print( x )
print( x.T ) # Transpose

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [315]:
v = np.array([1,2,3])
print(v)

[1 2 3]


In [317]:
print(v.T) #=> 1차원 array는 T가 안됨. (알아서 자동으로 처리하기 때문에 transpose가 무의미.)

[1 2 3]


# 5. Pandas  - Data Analysis

In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 1) Data Structure

In [45]:
from pandas import Series, DataFrame

### i) Series
- 1차원 list같은 자료구조.
- __index__에 각 데이터에 연관된 이름을 가지고 있음. -> id
- list로부터 생성가능.

In [46]:
obj = Series([4, 7, -5, 3])
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


In [47]:
# obj가 갖고 있는 데이터의 값 추출
obj.values

array([ 4,  7, -5,  3])

In [48]:
# obj가 갖고 있는 데이터의 index 추출
obj.index

RangeIndex(start=0, stop=4, step=1)

In [49]:
# index 임의로 지정 가능.
my_score = Series([93, 70, 96, 40], index=['Math', 'English', 'Science', 'Marketing'])
my_score

Math         93
English      70
Science      96
Marketing    40
dtype: int64

In [50]:
# obj2가 갖고 있는 데이터의 index 추출
my_score.index

Index(['Math', 'English', 'Science', 'Marketing'], dtype='object')

In [51]:
# 값에 접근할때는 index를 통해 접근.
my_score[2]

96

In [52]:
my_score['Math']

93

In [53]:
# 다수의 데이터에 접근할때는...
my_score['English','Marketing','Math']

KeyError: ('English', 'Marketing', 'Math')

In [418]:
# 없는 값에 접근하면...
my_score['Writing']

KeyError: 'Writing'

In [419]:
# 데이터 추가
my_score['Writing'] = 30

In [420]:
my_score

Math         93
English      70
Science      96
Marketing    40
Writing      30
dtype: int64

In [425]:
# 각 데이터에 산술연산 
my_score/10

Math         9.3
English      7.0
Science      9.6
Marketing    4.0
Writing      3.0
dtype: float64

In [427]:
# 특정 조건 데이터 추출 가능.
my_score[ my_score > 90 ]

Math       93
Science    96
dtype: int64

- 색인값에 데이터 값을 매핑하고 있으므로 파이썬의 사전형(dict)과 비슷

In [430]:
# 사전형처럼 사용 가능
'Math' in my_score

True

In [429]:
'Art' in my_score

False

In [443]:
# 사전형 객체로부터 Series 객체를 생성할 수도 있음!
your_score_dict = {"Math": 40, "English": 99, "Science":40, "Marketing":93}

In [444]:
your_score_dict

{'English': 99, 'Marketing': 93, 'Math': 40, 'Science': 40}

### Q) your_score의 데이터타입이 뭔지 알고 싶을때는..?

In [445]:
your_score = Series(your_score_dict)
your_score
# => 데이터 정렬이 값의 내림차순으로 정렬됨!

English      99
Marketing    93
Math         40
Science      40
dtype: int64

In [447]:
# index를 명시해서 문제해결.
your_score = Series(your_score_dict, index=['Math', 'English', 'Science', 'Marketing'])
your_score

Math         40
English      99
Science      40
Marketing    93
dtype: int64

In [448]:
my_score

Math         93
English      70
Science      96
Marketing    40
Writing      30
dtype: int64

### Q) my_score + your_score = ...?? 에러가 뜰까?

In [451]:
our_score = my_score + your_score

In [452]:
our_score

English      169.0
Marketing    133.0
Math         133.0
Science      136.0
Writing        NaN
dtype: float64

In [455]:
# .isnull() : 누락된 데이터인지 아닌지 판별.
our_score.isnull()

English      False
Marketing    False
Math         False
Science      False
Writing       True
dtype: bool

### ii) Dataframe
- R의 data.frame 같은 개념. -> __But.. Row와 Colomn에 대한 접근 개념이 반대.__
- 여러개의 column으로 이루어졌으며, 각 column은 서로 다른 종류의 값(숫자, 문자열, 불리언 등)을 담을 수 있음.
- 보통 같은 길이의 list에 담긴 사전형(dict)을 이용하거나 Numpy array를 이용함.

In [51]:
from pandas import DataFrame
import pandas as pd

In [55]:
score_data = {
    'name':['윤아', '혜리', '민호', '수지'],
    'class':['A', 'A', 'B', 'B'],
    'gender':['F', 'F','M','F'],
    'Math':[100, 90, 70, 60],
    'English':[90, 90, 100, 70]
}

In [56]:
score_smf = DataFrame(score_data)

In [57]:
score_smf

English  Math class gender name
0       90   100     A      F   윤아
1       90    90     A      F   혜리
2      100    70     B      M   민호
3       70    60     B      F   수지

In [61]:
# column명 명시하여 순서 조절 가능.
score_smf = DataFrame(score_data, columns=['name','class','gender','Math','English'])
score_smf

name class gender  Math  English
0   윤아     A      F   100       90
1   혜리     A      F    90       90
2   민호     B      M    70      100
3   수지     B      F    60       70

In [62]:
# .info() : 해당 DataFrame에 대한 정보 보여줌.
score_smf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
name       4 non-null object
class      4 non-null object
gender     4 non-null object
Math       4 non-null int64
English    4 non-null int64
dtypes: int64(2), object(3)
memory usage: 240.0+ bytes


In [63]:
# 요약통계량
score_smf.describe()

Math     English
count    4.000000    4.000000
mean    80.000000   87.500000
std     18.257419   12.583057
min     60.000000   70.000000
25%     67.500000   85.000000
50%     80.000000   90.000000
75%     92.500000   92.500000
max    100.000000  100.000000

In [64]:
score_smf.describe(include='all')

name class gender        Math     English
count     4     4      4    4.000000    4.000000
unique    4     2      2         NaN         NaN
top      민호     A      F         NaN         NaN
freq      1     2      3         NaN         NaN
mean    NaN   NaN    NaN   80.000000   87.500000
std     NaN   NaN    NaN   18.257419   12.583057
min     NaN   NaN    NaN   60.000000   70.000000
25%     NaN   NaN    NaN   67.500000   85.000000
50%     NaN   NaN    NaN   80.000000   90.000000
75%     NaN   NaN    NaN   92.500000   92.500000
max     NaN   NaN    NaN  100.000000  100.000000

In [65]:
# column 접근 방법 1) : 사전형 데이터처럼 접근
score_smf['Math']

0    100
1     90
2     70
3     60
Name: Math, dtype: int64

In [66]:
# column 접근 방법 2) : 속성 형식으로 접근.
score_smf.Math

0    100
1     90
2     70
3     60
Name: Math, dtype: int64

### Q) R처럼 column에 접근할 수는 없을까? 

In [67]:
score_smf[1]

KeyError: 1

In [68]:
score_smf[1:3]

name class gender  Math  English
1   혜리     A      F    90       90
2   민호     B      M    70      100

In [74]:
# row 접근 방법 : .iloc[~] 의 index로 접근 
score_smf.iloc[1]

name       혜리
class       A
gender      F
Math       90
English    90
Name: 1, dtype: object

In [75]:
# 새로운 column 추가
score_smf['isHuman'] = True
score_smf

name class gender  Math  English  isHuman
0   윤아     A      F   100       90     True
1   혜리     A      F    90       90     True
2   민호     B      M    70      100     True
3   수지     B      F    60       70     True

In [76]:
# column 삭제
del score_smf['isHuman']
score_smf

name class gender  Math  English
0   윤아     A      F   100       90
1   혜리     A      F    90       90
2   민호     B      M    70      100
3   수지     B      F    60       70

In [101]:
# 외부 데이터 로드
scores = pd.read_csv("data/scores.csv")
scores

Stu_ID  grade class gender  Math  English  Science  Marketing  Writing
0     10101      1     A      M    55       84       49         40       59
1     10102      1     A      M    29       94       27         87       57
2     10103      1     A      F    28       80       27         41      100
3     10104      1     A      F    45       74       40         88       75
4     10105      1     A      F    28       69       28         91       10
5     10106      1     A      M    86       51       75         59       92
6     10107      1     A      M    47       52       43         81       79
7     10108      1     A      F    80       67      100         85       90
8     10109      1     A      M    30       32       27         86       52
9     10110      1     A      M    94       39       84         67       28
10    10111      1     A      M    27       61       27         29      100
11    10112      1     A      M    88       39       75         70       87
12    10113      1     A      M    27      100       26         80       28
13    10114      1     A      F    35       70       33         51       34
14    10115      1     A      F    60       61       52         85       59
15    10116      1     A      F    58       66       52         72       94
16    10117      1     A      M    25       83       24         81       50
17    10118      1     A      F    54       82       48         42       91
18    10119      1     A      M    98       35       86         55       42
19    10120      1     A      F    50       91       43         71       95
20    10121      1     A      F    60       99       54         77       66
21    10122      1     A      M    91       84       78        100       56
22    10123      1     A      M    51       41       45         37       27
23    10124      1     A      F    76       63       65         47       28
24    10125      1     A      F    62       96       54         55       59
25    10126      1     A      M    29       29       27         71       72
26    10127      1     A      F    56       73       51         63       86
27    10128      1     A      F    92       59       79         96       83
28    10129      1     A      F    44       93       39         38       69
29    10130      1     A      F    48       49       44         67       87
..      ...    ...   ...    ...   ...      ...      ...        ...      ...
570   30511      3     E      F    53       36       47         34       27
571   30512      3     E      M    47       75       43         60       73
572   30513      3     E      M    48       65       45         38       65
573   30514      3     E      F    47       53       42         77       45
574   30515      3     E      F    39       72       33         95       95
575   30516      3     E      M    80       86       70         77       64
576   30517      3     E      F    85       64       75         68       48
577   30518      3     E      F    70       89       60         39       46
578   30519      3     E      M    70       41       61         28       50
579   30520      3     E      F    73       83       64         93       70
580   30521      3     E      M    83       26       72         29       77
581   30522      3     E      F   100       56       87         73       55
582   30523      3     E      F    41       99       39         59       33
583   30524      3     E      M    44       58       39         67       88
584   30525      3     E      M    59       51       51         86       75
585   30526      3     E      F    78       51       70         47       25
586   30527      3     E      M    31       29       29         55       83
587   30528      3     E      F    89       35       76         39       72
588   30529      3     E      M    39       45       37         82       43
589   30530      3     E      F    80       41       71         98       62
590   30531      3     E      F    70       66       

In [104]:
# DataFrame.loc 으로 색인 [행이름 조건, 열이름 조건] 
scores.loc[:,:] #전부 
# scores.loc[:5,:] 
# scores.loc[:,'Math'] 
# scores.loc[:,['Math','English']]
# scores.loc[10:20,['Math','English']]

Stu_ID  grade class gender  Math  English  Science  Marketing  Writing
0     10101      1     A      M    55       84       49         40       59
1     10102      1     A      M    29       94       27         87       57
2     10103      1     A      F    28       80       27         41      100
3     10104      1     A      F    45       74       40         88       75
4     10105      1     A      F    28       69       28         91       10
5     10106      1     A      M    86       51       75         59       92
6     10107      1     A      M    47       52       43         81       79
7     10108      1     A      F    80       67      100         85       90
8     10109      1     A      M    30       32       27         86       52
9     10110      1     A      M    94       39       84         67       28
10    10111      1     A      M    27       61       27         29      100
11    10112      1     A      M    88       39       75         70       87
12    10113      1     A      M    27      100       26         80       28
13    10114      1     A      F    35       70       33         51       34
14    10115      1     A      F    60       61       52         85       59
15    10116      1     A      F    58       66       52         72       94
16    10117      1     A      M    25       83       24         81       50
17    10118      1     A      F    54       82       48         42       91
18    10119      1     A      M    98       35       86         55       42
19    10120      1     A      F    50       91       43         71       95
20    10121      1     A      F    60       99       54         77       66
21    10122      1     A      M    91       84       78        100       56
22    10123      1     A      M    51       41       45         37       27
23    10124      1     A      F    76       63       65         47       28
24    10125      1     A      F    62       96       54         55       59
25    10126      1     A      M    29       29       27         71       72
26    10127      1     A      F    56       73       51         63       86
27    10128      1     A      F    92       59       79         96       83
28    10129      1     A      F    44       93       39         38       69
29    10130      1     A      F    48       49       44         67       87
..      ...    ...   ...    ...   ...      ...      ...        ...      ...
570   30511      3     E      F    53       36       47         34       27
571   30512      3     E      M    47       75       43         60       73
572   30513      3     E      M    48       65       45         38       65
573   30514      3     E      F    47       53       42         77       45
574   30515      3     E      F    39       72       33         95       95
575   30516      3     E      M    80       86       70         77       64
576   30517      3     E      F    85       64       75         68       48
577   30518      3     E      F    70       89       60         39       46
578   30519      3     E      M    70       41       61         28       50
579   30520      3     E      F    73       83       64         93       70
580   30521      3     E      M    83       26       72         29       77
581   30522      3     E      F   100       56       87         73       55
582   30523      3     E      F    41       99       39         59       33
583   30524      3     E      M    44       58       39         67       88
584   30525      3     E      M    59       51       51         86       75
585   30526      3     E      F    78       51       70         47       25
586   30527      3     E      M    31       29       29         55       83
587   30528      3     E      F    89       35       76         39       72
588   30529      3     E      M    39       45       37         82       43
589   30530      3     E      F    80       41       71         98       62
590   30531      3     E      F    70       66       

In [107]:
# DataFrame.iloc으로 인덱스로 색인
# scores.iloc[:,:] # 전부
scores.iloc[1:5,2:5]

class gender  Math
1     A      M    29
2     A      F    28
3     A      F    45
4     A      F    28